---
new_page_extension: md
auto_deploy: true
admin_path: "/static/admin"
webhook_url: 
sections:
  products:
    default_front_matter_template: products
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
